### ISSUE TITLE
How to get VSIX URL?

### ISSUE THREAD

**Issue by MoSkinny** [JCapriotti/chocolatey#4]
Hello, This package looks great! The only problem I'm having is... how do I get the URL of the VSIX file for the extension I want to install from the visual studio marketplace? Will this URL point to a specific version of the package or will it install the latest? I tried to referencing it by https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaid (which would be easy) for example but no luck. 

Thanks for the help

**Comment by JCapriotti** [comment]
Not sure if there is an easier way, but if you can use Dev Tools in Chrome, open it up and look at the Network Activity. Then click on the Download link and you should be able to see the URL. For the one you mentioned, it looks like this: https://visualstudiogallery.msdn.microsoft.com/76293c4d-8c16-4f4a-aee6-21f83a571496/file/9356/38/CodeMaid%20v10.2.7.vsix

When I wrote this, extensions came from a different site. Hopefully these newer URLs are static.

**Comment by MoSkinny** [comment]
Thanks so much...
